// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM2i6o6NNAlRJw4FCLOnDCW7tQd-eKW4c',
    appId: '1:937914090303:web:78d6c7c5e57c6a851f898a',
    messagingSenderId: '937914090303',
    projectId: 'sakar-a6fd5',
    authDomain: 'sakar-a6fd5.firebaseapp.com',
    databaseURL: 'https://sakar-a6fd5.firebaseio.com',
    storageBucket: 'sakar-a6fd5.appspot.com',
    measurementId: 'G-ETWTPR87ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvl6B3PzUkfLGIuolFTIVCMx_AsL0cnvE',
    appId: '1:937914090303:android:399d984de95a738f1f898a',
    messagingSenderId: '937914090303',
    projectId: 'sakar-a6fd5',
    databaseURL: 'https://sakar-a6fd5.firebaseio.com',
    storageBucket: 'sakar-a6fd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ9Ri2SPFZd1Y0BC3frZAGAdTlRrj3ECw',
    appId: '1:937914090303:ios:86091afe2b84bbf01f898a',
    messagingSenderId: '937914090303',
    projectId: 'sakar-a6fd5',
    databaseURL: 'https://sakar-a6fd5.firebaseio.com',
    storageBucket: 'sakar-a6fd5.appspot.com',
    androidClientId: '937914090303-2te217mg2tancg3o1meurdhohh5lk9na.apps.googleusercontent.com',
    iosClientId: '937914090303-i53qrhcud6033d6ft4oug75r6kp5kf96.apps.googleusercontent.com',
    iosBundleId: 'app.datacode.wecode.wecode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ9Ri2SPFZd1Y0BC3frZAGAdTlRrj3ECw',
    appId: '1:937914090303:ios:86091afe2b84bbf01f898a',
    messagingSenderId: '937914090303',
    projectId: 'sakar-a6fd5',
    databaseURL: 'https://sakar-a6fd5.firebaseio.com',
    storageBucket: 'sakar-a6fd5.appspot.com',
    androidClientId: '937914090303-2te217mg2tancg3o1meurdhohh5lk9na.apps.googleusercontent.com',
    iosClientId: '937914090303-i53qrhcud6033d6ft4oug75r6kp5kf96.apps.googleusercontent.com',
    iosBundleId: 'app.datacode.wecode.wecode',
  );
}
